-- DROP FUNCTION mySum;
DROP FUNCTION sum_he;

-- CREATE AGGREGATE FUNCTION mySum RETURNS INTEGER SONAME 'libsum.so';

CREATE AGGREGATE FUNCTION sum_he RETURNS STRING SONAME 'libsum.so';

SELECT * FROM mysql.func;