-- DROP FUNCTION mySum;
DROP FUNCTION SUM_HE;

-- CREATE AGGREGATE FUNCTION mySum RETURNS INTEGER SONAME 'libsum.so';

CREATE AGGREGATE FUNCTION SUM_HE RETURNS STRING SONAME 'libsum.so';

SELECT * FROM mysql.func;